### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by apyasic**
During the work on WDP Streaming Pipelines we were required to develop integration with message hub running on bluemix. Obviously, we’ve initially used the messaging toolkit Kafka capabilities. Unfortunately, it turned out that we could not use out-of-the-box version of the messaging toolkit due to lack of jars required for message hub authentication. So, we end-up with two copies of the messaging toolkit – the custom one and the out-of-the box one.
Due to the structure of our makefile, both custom and system toolkit PATHES should appear in the toolkit compile path definition WITHOUT explicit toolkit name specification in info.xml which creates conflicts in version precedence management especially on the bluemix streams service upgrade. To avoid such conflicts in the future, Kafka capabilities were separated from the core messaging toolkit.
This is an initial version of the com.ibm.streamsx.kafka toolkit. At this stage, no extensions were added to the toolkit logic, but the minimal set of changes required for toolkits separation, like:
-	Kafka related sources movement to com.ibm.streamsx.kafka namespace
-	Messagehub login jars were added to com.ibm.streamsx.kafka/opt/messagehub
-	Operators library path were extended with the path above
-	Build.xml and pom.xml were fixed to cope with the new namespaces. Specifically, pom.xml were restricted to download kafka specific libraries only
-	Kafka-related samples and benchmark were fixed accordingly as well

### CODE REVIEW

**Comment by schulz2** [comment]
Why didn't you copy the 'pom-kafka-0.9.xml' file, too, into the new project?

**Comment by schulz2** [comment]
Did you touch base with James Cancilla or Alex Cook before you started to split the code? There are 20 open issues for Kafka in streamsx.messaging, five of which are bugs. It probably would have been more effective to do corrections/enhancements first, don't you agree?

**Comment by apyasic** [comment]
Norbert, James is aware of the pull request. The purpose of the pull request is to create an initial separation with no bug fixes. The ''pom-kafka-0.9.xml' file would be added.

**Comment by cancilla** [comment]
@apyasic I appreciate your involvement with splitting out this toolkit. I am still in the process of deciding whether to use the existing toolkit as a baseline or start from the scratch as there are a number of parameter changes as well as changes to consistent region support that need to be implemented. The toolkit you have split will be a good reference while developing the first version of the Kafka toolkit. 

That being said, I would like to ask that you to modify this pull request to have the code merged into the "init_split" branch. I am following the Gitflow development process and the "master" branch is being reserved for production releases only.

**Comment by schulz2** [comment]
@cancilla, @apyasic, @cooka:
Can we touch base together so that we learn from each others time restrictions and discuss how to handle the open issues? I was in contact with Alex Cook already and we wanted to discuss the Consistent Region issues this week. He also has some time to spend in helping out.

**Comment by apyasic** [comment]
@cancilla per your request the new pull request https://github.com/IBMStreams/streamsx.kafka/pull/2 is opened against "init_split" branch.
@schulz2 the new pull request already contains modified 'pom-kafka-0.9.xml' file.

**Comment by cancilla** [comment]
Merged pull request #2 into **init_split** branch. Closing this pull request.

**Pull request closed without merging**
